hotfix: let compilation work
When compiling in debug mode, the 'inline' semantics of C99 led to the errors:

/roux/w25/openairinterface5g/common/utils/LOG/log.c:479: undefined reference to `log_header'
libUTIL.a(log.c.o): In function `log_dump':
/roux/w25/openairinterface5g/common/utils/LOG/log.c:502: undefined reference to `log_header'
collect2: error: ld returned 1 exit status

Let's use static instead of inline.